(function(){
  'use strict';
  function api(){return window.TRACNGHIEM||{};}
  function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function root(){return document.getElementById('app');}
  function layout(body){root().innerHTML=`<div class="wrap"><header class="top"><div><div class="brand">KHO TRẮC NGHIỆM ĐA MÔN</div><span class="tag">AI nhập câu hỏi • Admin duyệt trước khi lưu</span></div><div class="nav"><button class="btn" onclick="go('admin')">Admin</button><button class="btn" onclick="go('home')">Môn học</button></div></header>${body}</div>`;}
  function panel(){
    layout(`<section class="card"><button class="btn" onclick="go('admin')">← Admin</button><h2>AI nhập & tạo câu hỏi</h2><p class="muted">Có 3 cách: tạo bằng AI, quét ảnh đề, hoặc dán URL. Kết quả luôn được xem trước và duyệt trước khi lưu.</p></section>
    <section class="grid three">
      <button class="card tool" onclick="aiGeneratePanel()"><h3>🤖 AI tạo câu hỏi</h3><p class="muted">Nhập môn, bài, số câu, độ khó.</p></button>
      <button class="card tool" onclick="aiOCRPanel()"><h3>📷 Quét ảnh</h3><p class="muted">Chọn một hoặc nhiều ảnh đề/câu hỏi.</p></button>
      <button class="card tool" onclick="aiURLPanel()"><h3>🔗 Nhập URL</h3><p class="muted">Dán link trang có nội dung câu hỏi.</p></button>
    </section>`);
  }
  function aiGeneratePanel(){
    layout(`<section class="card"><button class="btn" onclick="aiPanel()">← AI</button><h2>🤖 AI tạo câu hỏi</h2><div class="grid two"><div><div class="field"><label>Môn</label><input id="gSubject" placeholder="Địa lí 12"></div><div class="field"><label>Bài/chủ đề</label><input id="gLesson" placeholder="Bài 1"></div><div class="field"><label>Số câu</label><input id="gCount" type="number" min="1" max="100" value="10"></div><div class="field"><label>Độ khó</label><select id="gDiff"><option value="mixed">Trộn</option><option value="nhan_biet">Nhận biết</option><option value="thong_hieu">Thông hiểu</option><option value="van_dung">Vận dụng</option></select></div></div><div><div class="field"><label>Nội dung nguồn</label><textarea id="gSource" placeholder="Dán tài liệu/bài học nếu muốn AI bám sát nguồn..." rows="9"></textarea></div><div class="field"><label>Yêu cầu</label><textarea id="gExtra" placeholder="Ví dụ: 4 lựa chọn, chỉ 1 đáp án đúng, không hỏi mơ hồ..." rows="5"></textarea></div></div></div><button class="btn primary" onclick="runAIGenerate()">TẠO CÂU HỎI</button><div id="aiPreview"></div></section>`);
  }
  function aiOCRPanel(){
    layout(`<section class="card"><button class="btn" onclick="aiPanel()">← AI</button><h2>📷 Quét ảnh đề</h2><p class="muted">Có thể chọn nhiều ảnh. AI sẽ nhận diện câu hỏi, A/B/C/D và đáp án nếu tài liệu có thể xác định.</p><div class="field"><label>Ảnh đề/câu hỏi</label><input id="ocrFiles" type="file" accept="image/*" multiple></div><div class="grid two"><div class="field"><label>Môn (tuỳ chọn)</label><input id="ocrSubject" placeholder="Toán"></div><div class="field"><label>Bài/chủ đề (tuỳ chọn)</label><input id="ocrLesson" placeholder="Chương 1"></div></div><button class="btn primary" onclick="runOCR()">QUÉT ẢNH BẰNG AI</button><div id="aiPreview"></div></section>`);
  }
  function aiURLPanel(){
    layout(`<section class="card"><button class="btn" onclick="aiPanel()">← AI</button><h2>🔗 Nhập câu hỏi từ URL</h2><p class="muted">Dán URL công khai. Chỉ sử dụng nội dung mà bạn có quyền sử dụng.</p><div class="field"><label>URL</label><input id="urlInput" type="url" placeholder="https://..."></div><div class="grid two"><div class="field"><label>Môn (tuỳ chọn)</label><input id="urlSubject"></div><div class="field"><label>Bài/chủ đề (tuỳ chọn)</label><input id="urlLesson"></div></div><div class="field"><label>Số câu tối đa</label><input id="urlCount" type="number" value="30" min="1" max="100"></div><button class="btn primary" onclick="runURLImport()">ĐỌC URL BẰNG AI</button><div id="aiPreview"></div></section>`);
  }
  function preview(items, source){
    const box=document.getElementById('aiPreview');
    window.__AI_IMPORT_ITEMS=items||[];
    box.innerHTML=`<div class="notice"><b>${items.length} câu được nhận diện.</b> Kiểm tra lại trước khi lưu.</div>`+items.map((q,i)=>`<section class="card ai-q"><div class="row"><b>Câu ${i+1}</b><button class="btn" onclick="removeAIQuestion(${i})">Xóa</button></div><div class="field"><label>Nội dung</label><textarea data-q="${i}" data-f="question_text" rows="3">${esc(q.question_text||'')}</textarea></div><div class="grid two">${[0,1,2,3].map(j=>`<div class="field"><label>${String.fromCharCode(65+j)}</label><input data-q="${i}" data-f="opt${j}" value="${esc((q.options||[])[j]||'')}"></div>`).join('')}</div><div class="grid two"><div class="field"><label>Đáp án đúng</label><select data-q="${i}" data-f="answer_index">${[0,1,2,3].map(j=>`<option value="${j}" ${Number(q.answer_index)===j?'selected':''}>${String.fromCharCode(65+j)}</option>`).join('')}</select></div><div class="field"><label>Độ khó</label><select data-q="${i}" data-f="difficulty"><option value="nhan_biet">Nhận biết</option><option value="thong_hieu">Thông hiểu</option><option value="van_dung">Vận dụng</option></select></div></div><div class="field"><label>Giải thích (tuỳ chọn)</label><textarea data-q="${i}" data-f="explanation" rows="2">${esc(q.explanation||'')}</textarea></div></section>`).join('')+`<button class="btn primary" onclick="saveAIQuestions('${esc(source||'AI')}')">DUYỆT VÀ LƯU ${items.length} CÂU</button>`;
  }
  window.removeAIQuestion=function(i){window.__AI_IMPORT_ITEMS.splice(i,1);preview(window.__AI_IMPORT_ITEMS,'AI');};
  function collect(){const items=window.__AI_IMPORT_ITEMS||[];return items.map((q,i)=>{const o={...q,options:[0,1,2,3].map(j=>document.querySelector(`[data-q="${i}"][data-f="opt${j}"]`)?.value||'')};o.question_text=document.querySelector(`[data-q="${i}"][data-f="question_text"]`)?.value||'';o.answer_index=Number(document.querySelector(`[data-q="${i}"][data-f="answer_index"]`)?.value||0);o.difficulty=document.querySelector(`[data-q="${i}"][data-f="difficulty"]`)?.value||'thong_hieu';o.explanation=document.querySelector(`[data-q="${i}"][data-f="explanation"]`)?.value||'';return o;});}
  window.saveAIQuestions=async function(){
    const A=api(), items=collect(); if(!A.sb)return alert('Supabase chưa kết nối.'); if(!items.length)return alert('Không có câu hỏi để lưu.');
    const subjectName=document.getElementById('gSubject')?.value||document.getElementById('ocrSubject')?.value||document.getElementById('urlSubject')?.value||'';
    const lessonName=document.getElementById('gLesson')?.value||document.getElementById('ocrLesson')?.value||document.getElementById('urlLesson')?.value||'';
    let subjectId=null, lessonId=null;
    if(subjectName){const s=await A.sb.from('subjects').select('id').ilike('name',subjectName).limit(1).maybeSingle();subjectId=s.data?.id||null;}
    if(lessonName&&subjectId){const l=await A.sb.from('lessons').select('id').eq('subject_id',subjectId).ilike('title',lessonName).limit(1).maybeSingle();lessonId=l.data?.id||null;}
    const rows=items.map(q=>({subject_id:subjectId,lesson_id:lessonId,question_text:q.question_text,options:q.options,answer_index:q.answer_index,explanation:q.explanation||null,difficulty:q.difficulty||'thong_hieu',source_text:q.source_text||null,created_by:A.state?.user?.id||null,approved:true}));
    const r=await A.sb.from('questions').insert(rows); if(r.error)return alert(r.error.message); alert(`Đã lưu ${items.length} câu vào ngân hàng.`);go('admin');
  };
  async function callFn(path,body){const A=api();if(!A.sb)return {error:'Supabase chưa kết nối.'};const session=await A.sb.auth.getSession();const token=session.data.session?.access_token;if(!token)return {error:'Phiên Admin đã hết hạn. Đăng nhập lại.'};try{const r=await fetch(A.config.SUPABASE_URL+'/functions/v1/'+path,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token,'apikey':A.config.SUPABASE_ANON_KEY},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)return {error:d.error||d.message||`HTTP ${r.status}`};return d;}catch(e){return {error:e.message};}}
  window.runAIGenerate=async function(){const box=document.getElementById('aiPreview');box.innerHTML='<div class="notice">AI đang tạo câu hỏi...</div>';const d=await callFn('ai-generate',{subject:document.getElementById('gSubject').value,lesson:document.getElementById('gLesson').value,count:Number(document.getElementById('gCount').value),difficulty:document.getElementById('gDiff').value,source:document.getElementById('gSource').value,extra:document.getElementById('gExtra').value});if(d.error)return box.innerHTML=`<div class="notice">${esc(d.error)}</div>`;preview(d.questions||[],'AI');};
  window.runOCR=async function(){const files=[...(document.getElementById('ocrFiles').files||[])];if(!files.length)return alert('Chọn ít nhất 1 ảnh.');const box=document.getElementById('aiPreview');box.innerHTML='<div class="notice">Đang đọc ảnh...</div>';const images=[];for(const f of files){if(f.size>8*1024*1024)return alert('Mỗi ảnh nên dưới 8 MB.');images.push({name:f.name,data:await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f);})});}const d=await callFn('ai-ocr',{images,subject:document.getElementById('ocrSubject').value,lesson:document.getElementById('ocrLesson').value});if(d.error)return box.innerHTML=`<div class="notice">${esc(d.error)}</div>`;preview(d.questions||[],'OCR');};
  window.runURLImport=async function(){const url=document.getElementById('urlInput').value.trim();if(!url)return alert('Dán URL trước.');const box=document.getElementById('aiPreview');box.innerHTML='<div class="notice">Đang đọc URL...</div>';const d=await callFn('ai-url',{url,subject:document.getElementById('urlSubject').value,lesson:document.getElementById('urlLesson').value,count:Number(document.getElementById('urlCount').value)});if(d.error)return box.innerHTML=`<div class="notice">${esc(d.error)}</div>`;preview(d.questions||[],'URL');};
  window.aiPanel=panel;window.aiGeneratePanel=aiGeneratePanel;window.aiOCRPanel=aiOCRPanel;window.aiURLPanel=aiURLPanel;
})();
